(require 'fastnav)
(global-set-key (kbd "C-c m z") 'fastnav-zap-up-to-char-forward)
(global-set-key (kbd "C-c m Z") 'fastnav-zap-up-to-char-backward)
(global-set-key (kbd "C-c m S") 'fastnav-jump-to-char-backward)
(global-set-key (kbd "C-c m r") 'fastnav-replace-char-forward)
(global-set-key (kbd "C-c m R") 'fastnav-replace-char-backward)
(global-set-key (kbd "C-c m i") 'fastnav-insert-at-char-forward)
(global-set-key (kbd "C-c m I") 'fastnav-insert-at-char-backward)
(global-set-key (kbd "C-c m j") 'fastnav-execute-at-char-forward)
(global-set-key (kbd "C-c m J") 'fastnav-execute-at-char-backward)
(global-set-key (kbd "C-c m k") 'fastnav-delete-char-forward)
(global-set-key (kbd "C-c m K") 'fastnav-delete-char-backward)
(global-set-key (kbd "C-c m m") 'fastnav-mark-to-char-forward)
(global-set-key (kbd "C-c m M") 'fastnav-mark-to-char-backward)

(global-set-key (kbd "C-c m p") 'fastnav-sprint-forward)
(global-set-key (kbd "C-c m P") 'fastnav-sprint-backward)
